server.port: 8081

# ????????? ??? ??????????? ? PostgresSQL


spring.datasource:
  url= jdbc:postgresql://localhost:5432/brunoyam
  username= postgres
  password= postgres

spring.jpa.hibernate.ddl-auto: create